# Generated by Django 4.2 on 2023-05-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('codarea', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desarea', models.CharField(max_length=30, unique=True)),
                ('tipoarea', models.CharField(max_length=2)),
                ('activa', models.BooleanField()),
                ('codent', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('codfamilia', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('desfami', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UM',
            fields=[
                ('codum', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('descum', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codprod', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('cantvend', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechventa', models.DateField()),
                ('codarea', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codprod', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('desprod', models.CharField(max_length=50, unique=True)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precventa', models.DecimalField(decimal_places=4, max_digits=10)),
                ('codum', models.CharField(max_length=50, unique=True)),
                ('codfamilia', models.CharField(max_length=8, unique=True)),
                ('area', models.ManyToManyField(to='CaptaVenta.areas')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaptaVenta.familia')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaptaVenta.um')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CaptaVenta.venta'),
        ),
    ]
